// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4nUlY09B7KXrdusHGshN6dwl6C-wTwQ',
    appId: '1:546072951222:web:b52d9fd5dd9249f4046917',
    messagingSenderId: '546072951222',
    projectId: 'job-timer-project-123123',
    authDomain: 'job-timer-project-123123.firebaseapp.com',
    storageBucket: 'job-timer-project-123123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl9c6KFoTXFiMu1DNvFXupNny9n7CNHhI',
    appId: '1:546072951222:android:1a5a4609a52d103e046917',
    messagingSenderId: '546072951222',
    projectId: 'job-timer-project-123123',
    storageBucket: 'job-timer-project-123123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkfAqHWHlfyWj-EMv3TmSJGeH7aEr1pzM',
    appId: '1:546072951222:ios:5e2218b05341d34b046917',
    messagingSenderId: '546072951222',
    projectId: 'job-timer-project-123123',
    storageBucket: 'job-timer-project-123123.appspot.com',
    iosBundleId: 'com.example.jobTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkfAqHWHlfyWj-EMv3TmSJGeH7aEr1pzM',
    appId: '1:546072951222:ios:5e2218b05341d34b046917',
    messagingSenderId: '546072951222',
    projectId: 'job-timer-project-123123',
    storageBucket: 'job-timer-project-123123.appspot.com',
    iosBundleId: 'com.example.jobTimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT4nUlY09B7KXrdusHGshN6dwl6C-wTwQ',
    appId: '1:546072951222:web:a571054e182542a2046917',
    messagingSenderId: '546072951222',
    projectId: 'job-timer-project-123123',
    authDomain: 'job-timer-project-123123.firebaseapp.com',
    storageBucket: 'job-timer-project-123123.appspot.com',
  );
}
